name = "vno-hugo"
license = "CC BY 4.0"
licenselink = "https://creativecommons.org/licenses/by/4.0/"
description = "Vno Hugo is a port of Vno Jekyll."
homepage = "https://github.com/xslingcn/vno-hugo"
tags = ["blog", "responsive"]
features = ["blog", "responsive"]
min_version = "0.58.0"

# If the theme has a single author
[author]
    name = "xsling"
    homepage = "https://github.com/xslingcn"

# If porting an existing theme
[original]
    author = "onevcat"
    homepage = "https://onevcat.com/"
    repo = "https://github.com/onevcat/vno-jekyll"